### ISSUE TITLE
[Feature Request] Support HTTPS_PROXY as proxy

### ISSUE THREAD

**Issue by PeterlitsZo** [honojs/create-hono#17]
I notice that the project is using `degit` to get the template in GitHub. But I find that `degit` does not support `HTTPS_PROXY` which other application or library does.

I create a PR for degit and a issue for tiged (https://github.com/tiged/tiged/issues/86). I hope that it can really be supported well.

**Comment by yusukebe** [comment]
Thanks. I too want this feature!

**Comment by PeterlitsZo** [comment]
Hello @yusukebe I and @nake89 add nice commit into `tiged`. Now it can also support `HTTPS_PROXY` as proxy.

But the question is do you guys think using tiged rather than degit is a better idea? In my opinion it sounds great. If you guys also think so, I will check the differences from degit and tiged to make sure using tiged is safe.

**Comment by nake89** [comment]
I haven't yet published the npm package update yet. But it is in the main branch. I want to make sure it actually works. Behind the scenes it is using `https.get` and passing a `new Agent()` with the proxy properties. But something about it doesn't look right. Maybe it works. But I'm gonna test it soon when I have time.

Reason to update to tiged: Degit is not actively maintained and contains lots of bugs which have been fixed in tiged.

Repo: https://github.com/tiged/tiged/
Here is a non-comprehensive list of fixes: https://github.com/tiged/tiged?tab=readme-ov-file#what-has-been-fixed
Changelog for more detail: https://github.com/tiged/tiged/blob/main/CHANGELOG.md

Full disclosure: I am creator and maintainer of tiged, a community maintained for of degit.

**Comment by yusukebe** [comment]
Yeah. Using `tiged` is a good idea! If @nake89's work goes well, I want to replace `degit` in `create-hono` with `tiged`.

**Comment by nake89** [comment]
Newest version now has this feature.
