### ISSUE TITLE
Stop using `tiged`

### ISSUE THREAD

**Issue by goisaki** [honojs/create-hono#50]
Currently `create-hono` uses `tiged` to download templates, but since this is not dynamic and the data size is small, it would be better to include the templates themselves in `create-hono`. This change would reduce package size and speed up project generation. It may be necessary to automatically update the package to match the template updates, but this is enough work to be worth the effect and I can make it myself.
If we plan to support 3rd-party repositories as templates in the future it makes sense to continue to rely on tiged. However, it is safe to assume that users with such advanced usage already have the `git` command installed; [the create-remix implementation](https://github.com/remix-run/remix/blob/e324b3e08c83f561f386bdc4a836308cd5249271/packages/create-remix/copy-template.ts#L181-L208) that downloads Github repositories as a zip can also be referenced.

**Comment by ryuapp** [comment]
I agree to stop using tiged.
In my opinion, I find it problematic that tiged depends on `git`.

Many users already have `git` installed, but beginners and people who have replaced their PC do not have `git` installed.
I often see people on Discord community who don't have `git` installed for some reason and can't use `create-hono`.
Also, that error is very confusing. This is the pain point.

We can do something like create-remix, but depending on a reliable library will reduce maintenance costs.
For example, giget:
https://github.com/unjs/giget

**Comment by yusukebe** [comment]
I also want to stop using `git` and make it not depend on `git`.

At first glance. Using giget is good.

**Comment by goisaki** [comment]
Hi @yusukebe @ryuapp @MathurAditya724 
Sorry for the ongoing implementation, but there is another way that is simplest and does not require git commands or heavy tiged etc.
It is to put the templates in `create-hono` itself. If we clone the templates with Git when we build, users can use `create-hono` without Git commands. And the experience would probably be better, as templates are lighter than tiged (at least for now) and don't call for additional network traffic.
This method would require more work than using third-party libraries, but the benefits are worth the cost. What do you think about this method?
See also [`create-vite`](https://github.com/vitejs/vite/tree/main/packages/create-vite) for the same method.

**Comment by MathurAditya724** [comment]
For using community templates in `vite` they suggest we use `degit` - https://github.com/vitejs/vite/tree/main/packages/create-vite#community-templates

In our case, we want to download the templates using `create-hono` because of the hooks, especially for Cloudflare-related templates. So even if we bundle the templates in `create-hono` we need something like `degit` to download external/community templates. These support caching and offline mode so once a user has used them they will be cached (Currently this is not supported but we can enable this in the future https://github.com/honojs/create-hono/pull/63#issuecomment-2262009192).

Also IMO, most users don't use more than 2 - 3 templates. I did comment about this approach here https://github.com/honojs/create-hono/issues/62#issuecomment-2260660377

**Comment by goisaki** [comment]
The recommended method of using `degit` to download community templates is very reasonable.
With `create-hono` we should focus on providing the best bug-free experience in common cases rather than how to support all cases.
So it is a good way to package the templates for this goal.
I would like to hear @yusukebe  and @ryuapp 's opinions, especially on the support for community templates.

**Comment by ryuapp** [comment]
I also think it's good to implement like `create-vite`. However, due to the configuration, maintainers will have to upload the package every time you update the Hono version in package.json. It takes time for them, so we need to think about it.

At least the current configuration is less time consuming.
