### ISSUE TITLE
Malwarebytes detects create-hono as Malware.Heuristic.2006

### ISSUE THREAD

**Issue by ezShroom** [honojs/create-hono#55]
![image](https://github.com/honojs/create-hono/assets/68300730/b2a3c558-b9cf-4966-a5da-a758b4480381)
Not much time to investigate this. Will leave it with y'all

**Comment by yusukebe** [comment]
I've tried scanned the file in this package with [VirusTotal](https://www.virustotal.com/gui/home/upload). But there is no security matter.

`package/bin`:

https://www.virustotal.com/gui/file/d496a007fb1761b5d8aac9ec2ef8e2e77af58f2c49852db117299e4c55449f6b?nocache=1

![CleanShot 2024-07-04 at 14 27 38@2x](https://github.com/honojs/create-hono/assets/10682/9aa0f257-5390-4fc9-9c35-e818a232001f)

`https://registry.npmjs.org/create-hono/-/create-hono-0.9.2.tgz`:
https://www.virustotal.com/gui/url/18e106983f75cc244d83dfef7eaefd70f2d5cd9f25f3520ef347507b64ede862

If you download it from `registry.npmjs.org`, it will be safe. But we can't handle the other repo's security issues since it's not Hono's scope. We can close this issue.

**Comment by ezShroom** [comment]
It was downloaded from npmjs, since it was done with Bun in an empty project.
