### ISSUE TITLE
feat: support for external templates

### ISSUE THREAD

**Issue by MathurAditya724** [honojs/create-hono#62]
Can we add support for `--template` or something through which we can use external templates?

This is how the usage will be `pnpm create hono@latest --template=repo_addr`. I understand that we can use `degit` but it's mainly useful because of the hooks.

If you want I can create the PR for this

**Comment by MathurAditya724** [comment]
Found this issue which is similar to this one - https://github.com/honojs/starter/issues/14, we can do something similar here.

**Comment by MathurAditya724** [comment]
I propose using `giget` to address the dependency on git. Embedding templates in create-hono may not be necessary because `giget` and similar tools can cache templates once downloaded, and most users typically use only 2-3 templates.

To implement this, we can use regex to determine the appropriate git provider for the templates. I need to investigate whether `giget` supports custom providers, but overall, this approach seems feasible.

Please let me know if you have any further concerns or suggestions. Otherwise, I will start working on the PR so we can evaluate this approach more thoroughly.

**Comment by yusukebe** [comment]
@MathurAditya724 

Cool! 

Shall we start to work on replacing `tiged` with `giget` (#50)? I think we have to think of these as separate issues that support external templates(#62) and replace `tiged` with `giget` (#50).

cc: @goisaki @ryuapp If you have any opinions on these issues, please share them. @MathurAditya724 can create a PR, and you can review it.

**Comment by MathurAditya724** [comment]
Created the first PR for removing `tiged` #63, Kindly have a look

**Comment by ryuapp** [comment]
It's hard to support completely external community templates.
`create-hono` should only support external templates that have been checked by Hono community.
For those that do not apply, we will guide you on how to download them using `giget` or `digit`.

The reason is security and reliability issues. 
For example, using `create-hono`, what the user expects to do is download a Hono template project. If we can download completely external projects, we can also download malicious ones. The same thing is possible with `giget`, but the reason the user use the command is to download templates, so the responsibility is clearly on you.

Therefore, I think that unless `create-hono` has any special functionality other than downloading templates, it should not support completely external templates. My concerns may disappear if a warning dialog is displayed.

**Comment by MathurAditya724** [comment]
I will start working on the new PR for adding `commander` described here https://github.com/honojs/create-hono/pull/63#issuecomment-2262009192. I believe it will benefit this issue because we need the `--template` option.

**Comment by yusukebe** [comment]
@MathurAditya724 

Still, we have to consider if it should have `--template` option or not.

I agree @ryuapp 's opinion:

> The reason is security and reliability issues.

**Comment by MathurAditya724** [comment]
This is how I have planned to resolve this issue, I have divided this issue into 3 parts (3 PRs) - 

1. Remove `tiged`, completed ✅
2. Introduce `commander` so that in place of always adding the options manually we can write them in a single line, eg - `pnpm create hono@latest my-app --template=cloudflare-workers -Y`. This will not add functionality for external templates, only CLI options for better DX.
3. The main PR to resolve this issue.

As for security, I agree with @ryuapp. Adding a warning banner when accessing 3rd party repositories seems like a good approach because hosting all the templates in a single repository can be challenging to maintain and scale.
